EXEC=sopwith
OBJFILE=${EXEC}.o

%.o: %.cpp
	$(CXX) $< -Wall -c -o $@ -O3 -s -DUNIX -DPANDORA -pipe -march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=softfp -ftree-vectorize -ffast-math -fsingle-precision-constant

${EXEC}:${OBJFILE}
	$(CXX) ${OBJFILE} -o ${EXEC} -Wall -O3 -L/mnt/utmp/sopwith/lib -lalleg

clean:
	rm -f ${EXEC} ${OBJFILE}
